DROP TABLE category;
DROP TABLE category_link;
DROP TABLE component;
DROP TABLE component_subset;
DROP TABLE page;
DROP TABLE spell;
DROP TABLE spell_category;
DROP TABLE spell_component;
DROP TABLE spell_product;